# -*- coding: utf-8 -*-
"""
Fonte de verdade da TABELA CANÔNICA de ingredientes.

Decisões tomadas manualmente (julgamento semântico) sobre os 404 nomes
canônicos de Ingredientes_Scrapping.xlsx. NÃO é heurística de regex —
cada nome bruto foi classificado à mão como:

  - ATOMICO[nome_bruto]  = nome_base            (ingrediente de varejo único)
  - COMPOSTO[nome_bruto] = [[base, proporção], ...]  (prato/preparo decomposto)

REVISAR[nome_bruto] = motivo  → marca pontos de baixa confiança para o
usuário focar a revisão (proporção estimada, nome ambíguo, etc.).

As proporções dos COMPOSTOS são ESTIMATIVAS minhas (não estão na planilha
original) e por isso quase todas estão marcadas em REVISAR.
"""

# ─── Vocabulário controlado de ingredientes-base (atômicos) ──────────────────
# nome_base -> categoria
BASE = {
    # Grãos / cereais / farináceos
    "Arroz branco":                 "Grão/Cereal",
    "Macarrão":                     "Grão/Cereal",
    "Fubá de milho":                "Grão/Cereal",
    "Flocão de milho (cuscuz)":     "Grão/Cereal",
    "Farinha de trigo":             "Grão/Cereal",
    "Farinha de rosca":             "Grão/Cereal",
    "Farinha de mandioca":          "Grão/Cereal",
    "Goma de tapioca":              "Grão/Cereal",
    "Pão francês":                  "Grão/Cereal",
    "Pão de alho (bisnaga)":        "Grão/Cereal",
    # Leguminosas
    "Feijão carioca":               "Leguminosa",
    "Feijão preto":                 "Leguminosa",
    "Feijão de corda":              "Leguminosa",
    "Feijão fradinho":              "Leguminosa",
    "Grão-de-bico":                 "Leguminosa",
    # Proteína bovina
    "Acém/Músculo bovino":          "Proteína bovina",
    "Alcatra bovina":               "Proteína bovina",
    "Contrafilé bovino":            "Proteína bovina",
    "Coxão mole bovino":            "Proteína bovina",
    "Coxão duro bovino":            "Proteína bovina",
    "Patinho bovino":               "Proteína bovina",
    "Chuleta bovina":               "Proteína bovina",
    "Filé mignon":                  "Proteína bovina",
    "Carne moída bovina":           "Proteína bovina",
    "Costela bovina":               "Proteína bovina",
    "Peito bovino":                 "Proteína bovina",
    "Matambre bovino":              "Proteína bovina",
    "Fígado bovino":                "Proteína bovina",
    "Rabada bovina":                "Proteína bovina",
    "Mocotó (pata bovina)":         "Proteína bovina",
    "Bucho/Dobradinha bovina":      "Proteína bovina",
    "Carne seca/Charque":           "Proteína bovina",
    "Carne de sol":                 "Proteína bovina",
    "Carne ovina (costela)":        "Proteína ovina/caprina",
    "Carne de bode":                "Proteína ovina/caprina",
    # Proteína suína
    "Bisteca suína":                "Proteína suína",
    "Lombo suíno":                  "Proteína suína",
    "Pernil suíno":                 "Proteína suína",
    "Costela suína":                "Proteína suína",
    "Panceta/Barriga suína":        "Proteína suína",
    "Bacon":                        "Proteína suína",
    "Torresmo":                     "Proteína suína",
    "Linguiça calabresa":           "Proteína suína",
    "Linguiça toscana (suína)":     "Proteína suína",
    "Linguiça defumada":            "Proteína suína",
    "Presunto":                     "Proteína suína",
    "Miúdos suínos":                "Proteína suína",
    # Proteína aves
    "Frango em pedaços (coxa/sobrecoxa)": "Proteína aves",
    "Peito de frango":              "Proteína aves",
    "Frango inteiro":               "Proteína aves",
    # Proteína pescado / frutos do mar
    "Merluza (filé)":               "Proteína pescado",
    "Tambaqui (peixe)":             "Proteína pescado",
    "Pintado (peixe)":              "Proteína pescado",
    "Pacu (peixe)":                 "Proteína pescado",
    "Pescada (peixe)":              "Proteína pescado",
    "Cavala (peixe)":               "Proteína pescado",
    "Tainha (peixe)":               "Proteína pescado",
    "Peixe de água doce (posta)":   "Proteína pescado",
    "Peixe de mar (posta)":         "Proteína pescado",
    "Pirarucu seco":                "Proteína pescado",
    "Camarão fresco":               "Proteína pescado",
    "Camarão seco":                 "Proteína pescado",
    "Carne de siri":                "Proteína pescado",
    "Sururu":                       "Proteína pescado",
    # Ovos
    "Ovo":                          "Ovos",
    # Gorduras / óleos
    "Óleo de soja":                 "Gordura/Óleo",
    "Azeite de oliva":              "Gordura/Óleo",
    "Azeite de dendê":              "Gordura/Óleo",
    "Banha suína":                  "Gordura/Óleo",
    # Laticínios
    "Manteiga":                     "Laticínio",
    "Manteiga de garrafa":          "Laticínio",
    "Creme de leite":               "Laticínio",
    "Leite":                        "Laticínio",
    "Leite de coco":                "Laticínio",
    "Queijo coalho":                "Laticínio",
    "Queijo mussarela":             "Laticínio",
    "Queijo prato":                 "Laticínio",
    "Queijo parmesão":              "Laticínio",
    # Tubérculos / raízes
    "Batata inglesa":               "Tubérculo/Raiz",
    "Batata palha":                 "Tubérculo/Raiz",
    "Batata doce":                  "Tubérculo/Raiz",
    "Mandioca":                     "Tubérculo/Raiz",
    "Banana da terra":              "Fruta",
    "Abóbora":                      "Legume/Verdura",
    # Legumes / verduras
    "Cenoura":                      "Legume/Verdura",
    "Tomate":                       "Legume/Verdura",
    "Cebola":                       "Tempero/Erva",
    "Cebola roxa":                  "Tempero/Erva",
    "Pimentão":                     "Legume/Verdura",
    "Couve":                        "Legume/Verdura",
    "Repolho":                      "Legume/Verdura",
    "Alface":                       "Legume/Verdura",
    "Rúcula":                       "Legume/Verdura",
    "Escarola/Chicória":            "Legume/Verdura",
    "Agrião":                       "Legume/Verdura",
    "Quiabo":                       "Legume/Verdura",
    "Palmito":                      "Legume/Verdura",
    "Guariroba":                    "Legume/Verdura",
    "Champignon (conserva)":        "Legume/Verdura",
    "Milho verde":                  "Legume/Verdura",
    "Pequi":                        "Fruta",
    "Jambu":                        "Legume/Verdura",
    "Maniva (folha de mandioca)":   "Legume/Verdura",
    "Laranja":                      "Fruta",
    "Limão":                        "Fruta",
    "Amendoim":                     "Outro",
    # Temperos / ervas
    "Alho":                         "Tempero/Erva",
    "Sal":                          "Tempero/Erva",
    "Cheiro-verde":                 "Tempero/Erva",
    "Coentro":                      "Tempero/Erva",
    "Pimenta (fresca)":             "Tempero/Erva",
    "Pimenta do reino":             "Tempero/Erva",
    "Colorau/Urucum":               "Tempero/Erva",
    "Açafrão da terra":             "Tempero/Erva",
    "Cominho":                      "Tempero/Erva",
    "Louro (folha)":                "Tempero/Erva",
    "Orégano":                      "Tempero/Erva",
    "Hortelã":                      "Tempero/Erva",
    "Manjericão":                   "Tempero/Erva",
    # Condimentos / molhos prontos
    "Vinagre":                      "Condimento/Molho",
    "Mostarda":                     "Condimento/Molho",
    "Ketchup":                      "Condimento/Molho",
    "Maionese":                     "Condimento/Molho",
    "Extrato de tomate":            "Condimento/Molho",
    "Molho de tomate (sachê)":      "Condimento/Molho",
    "Caldo de carne (tablete)":     "Condimento/Molho",
    "Cachaça":                      "Outro",
    # Líquidos regionais
    "Tucupi":                       "Líquido regional",
    "Açaí (polpa)":                 "Líquido regional",
    # Itens de preço fixo (não-scrapeáveis)
    "Sangue suíno":                 "Outro",
    "Sangue de aves":               "Outro",
    # Sentinelas
    "Água/Subproduto (sem custo)":  "Subproduto",
    "SEM COTAÇÃO (revisar)":        "Subproduto",
}

# ─── Mapeamento ATÔMICO: nome bruto -> nome-base ─────────────────────────────
ATOMICO = {
    # Arroz
    "Arroz": "Arroz branco",
    "Arroz agulhinha longo comercial": "Arroz branco",
    "Arroz Arbório ou branco especial longo": "Arroz branco",
    "Arroz branco": "Arroz branco",
    "Arroz branco brilhante refogado rápido": "Arroz branco",
    "Arroz branco comum longo": "Arroz branco",
    "Arroz branco cozido em fogo brando": "Arroz branco",
    "Arroz branco de acompanhamento": "Arroz branco",
    "Arroz branco de guarnição": "Arroz branco",
    "Arroz branco guarnição leve": "Arroz branco",
    "Arroz branco solto": "Arroz branco",
    "Arroz branco/agulhinha": "Arroz branco",
    "Arroz branco/parboilizado": "Arroz branco",
    "Arroz comercial agulhinha branco": "Arroz branco",
    "Arroz comercial cozido junto à carne na caçarola": "Arroz branco",
    "Arroz e Caldo da cocção servido copioso": "Arroz branco",
    # Macarrão
    "Espaguete (macarrão seco)": "Macarrão",
    "Espaguete ou Penne seco": "Macarrão",
    # Farináceos
    "Farinha": "Farinha de mandioca",
    "Farinha d'água": "Farinha de mandioca",
    "Farinha d'água / Tapioca": "Farinha de mandioca",
    "Farinha de mandioca": "Farinha de mandioca",
    "Farinha de mandioca branca": "Farinha de mandioca",
    "Farinha de mandioca d'água": "Farinha de mandioca",
    "Farinha de mandioca empane": "Farinha de mandioca",
    "Farinha de mandioca fina": "Farinha de mandioca",
    "Farinha de mandioca fina crua": "Farinha de mandioca",
    "Farinha de mandioca temperada": "Farinha de mandioca",
    "Farinha de mandioca tostada": "Farinha de mandioca",
    "Farinha de Uarini": "Farinha de mandioca",
    "Farinha de milho (cuscuz hidratado)": "Flocão de milho (cuscuz)",
    "Farinha de rosca grossa": "Farinha de rosca",
    "Farinha de rosca pesada": "Farinha de rosca",
    "Farinha de trigo": "Farinha de trigo",
    "Farinha de trigo branca": "Farinha de trigo",
    "Goma de mandioca (hidratada)": "Goma de tapioca",
    "Goma de tapioca": "Goma de tapioca",
    "Pão dormido": "Pão francês",
    "Pão dormido ou farinha de trigo": "Pão francês",
    "Pão francês ou torradas": "Pão francês",
    "Pão de alho bisnaga cremosa (forno)": "Pão de alho (bisnaga)",
    # Feijões
    "Feijão": "Feijão carioca",
    "Feijão caldo ralo": "Feijão carioca",
    "Feijão caldoso": "Feijão carioca",
    "Feijão caldoso caseiro": "Feijão carioca",
    "Feijão carioca": "Feijão carioca",
    "Feijão carioca cozido al dente": "Feijão carioca",
    "Feijão carioca espesso": "Feijão carioca",
    "Feijão com caldo": "Feijão carioca",
    "Feijão comum": "Feijão carioca",
    "Feijão de caldo": "Feijão carioca",
    "Feijão de caldo farto": "Feijão carioca",
    "Feijão engrossado": "Feijão carioca",
    "Feijão espesso": "Feijão carioca",
    "Feijão mexido sem caldo (acompanhamento)": "Feijão carioca",
    "Feijão caldo negro": "Feijão preto",
    "Feijão negro pesado": "Feijão preto",
    "Feijão preto (hidratação longa)": "Feijão preto",
    "Feijão marrom ou negro": "Feijão preto",
    "Feijão de corda": "Feijão de corda",
    "Feijão de corda / Feijão verde": "Feijão de corda",
    "Feijão de corda com caldo": "Feijão de corda",
    "Feijão macassa (feijão de corda)": "Feijão de corda",
    "Feijão manteiguinha (Santarém)": "Feijão de corda",
    "Feijão verde fresco": "Feijão de corda",
    "Feijão verde manteiguinha": "Feijão de corda",
    "Feijão fradinho cozido": "Feijão fradinho",
    "Massa de Feijão-fradinho puro": "Feijão fradinho",
    "Grão-de-bico demolhado farto": "Grão-de-bico",
    # Bovinos
    "Carne (Músculo ou Acém)": "Acém/Músculo bovino",
    "Carne bovina desfiada no molho com pressão": "Acém/Músculo bovino",
    "Bife bovino (Alcatra)": "Alcatra bovina",
    "Bife bovino fino da alcatra": "Alcatra bovina",
    "Bife bovino selado rapidamente (ponto macio)": "Coxão mole bovino",
    "Carne bovina (Contrafilé/Alcatra)": "Alcatra bovina",
    "Carne bovina cortada (iscas)": "Coxão mole bovino",
    "Carne em tiras (Alcatra/Mignon/Patinho)": "Alcatra bovina",
    "Bife (Coxão mole batido)": "Coxão mole bovino",
    "Bife de Coxão mole empanado": "Coxão mole bovino",
    "Carne em cubos (Coxão mole)": "Coxão mole bovino",
    "Bife enrolado (Coxão duro longo)": "Coxão duro bovino",
    "Carne picada (Coxão duro/Patinho)": "Patinho bovino",
    "Bife espesso batido de gado (patinho fino)": "Patinho bovino",
    "Bife grande de Contrafilé": "Contrafilé bovino",
    "Chuleta (contrafilé bovino gordo com osso)": "Chuleta bovina",
    "Filé Mignon alto": "Filé mignon",
    "Carne bovina moída": "Carne moída bovina",
    "Carne bovina moída crua": "Carne moída bovina",
    "Carne moída no molho denso": "Carne moída bovina",
    "Carne bovina ponta de agulha longa cocção": "Acém/Músculo bovino",
    "Costela bovina com osso espesso": "Costela bovina",
    "Costela de ripa (bovina gorda com osso)": "Costela bovina",
    "Costela/Alcatra/Vazio assados brasa (1 hora)": "Costela bovina",
    "Carnes do peito bovino forte": "Peito bovino",
    "Matambre bovino aberto": "Matambre bovino",
    "Fígado bovino em tiras": "Fígado bovino",
    "Fígado bovino limpo": "Fígado bovino",
    "Iscas ou bife de Fígado bovino": "Fígado bovino",
    "Rabada bovina com osso": "Rabada bovina",
    "Pata bovina (Mocotó)": "Mocotó (pata bovina)",
    "Miúdos bovinos (Bucho/Tripas limpas)": "Bucho/Dobradinha bovina",
    "Carne seca (charque/sol picada)": "Carne seca/Charque",
    "Carne seca desfiada temperada": "Carne seca/Charque",
    "Charque (Carne seca sulista fina)": "Carne seca/Charque",
    "Charque dessalgado e frito": "Carne seca/Charque",
    "charque magro": "Carne seca/Charque",
    "Carne de sol (contrafilé curado)": "Carne de sol",
    "Carne de sol em cubos": "Carne de sol",
    "Carne de sol fatiada e batida": "Carne de sol",
    "Carne de sol mantada": "Carne de sol",
    "Carne de sol pisada no pilão": "Carne de sol",
    "Carne ovina gorda da Campanha com osso (costela)": "Carne ovina (costela)",
    "Carne de bode com osso": "Carne de bode",
    # Suínos
    "Bisteca suína fina": "Bisteca suína",
    "Lombo suíno fatiado": "Lombo suíno",
    "Lombo/Pernil suíno em iscas": "Pernil suíno",
    "Costela suína fina": "Costela suína",
    "Panceta ou Barriga de porco limpa com couro": "Panceta/Barriga suína",
    "Bacon": "Bacon",
    "Toucinho/Bacon (camada fina para dar liga)": "Bacon",
    "Torresmo": "Torresmo",
    "Linguiça calabresa defumada": "Linguiça calabresa",
    "Linguiça calabresa fina": "Linguiça calabresa",
    "Linguiça de porco recheio": "Linguiça toscana (suína)",
    "Linguiça pura de pernil frita": "Linguiça toscana (suína)",
    "Linguiça toscana/calabresa de porco": "Linguiça toscana (suína)",
    "Salsichão campeiro (linguiça grossa de churrasco)": "Linguiça toscana (suína)",
    "Linguiça defumada": "Linguiça defumada",
    "Linguiça defumada Blumenau macia alemã": "Linguiça defumada",
    "Linguiça defumada suína gorda": "Linguiça defumada",
    "Presunto": "Presunto",
    "Presunto magro": "Presunto",
    "Miúdos de porco limpos (coração/fígado)": "Miúdos suínos",
    "Miúdos de porco/Carne seca": "Miúdos suínos",
    # Aves
    "Coxa/sobrecoxa avícola": "Frango em pedaços (coxa/sobrecoxa)",
    "Frango em pedaços (coxa/sobrecoxa)": "Frango em pedaços (coxa/sobrecoxa)",
    "Pedaços de frango cru": "Frango em pedaços (coxa/sobrecoxa)",
    "Pedaços de frango marinados com osso limpo": "Frango em pedaços (coxa/sobrecoxa)",
    "Sobrecoxa de frango assada de padaria": "Frango em pedaços (coxa/sobrecoxa)",
    "Sobrecoxa ou coxa avícola": "Frango em pedaços (coxa/sobrecoxa)",
    "Filé de peito avícola batido e empanado": "Peito de frango",
    "Filé de peito avícola fino (escalope)": "Peito de frango",
    "Peito avícola em cubos higienizados": "Peito de frango",
    "Peito de frango (desfiado)": "Peito de frango",
    "Peito de frango em cubos": "Peito de frango",
    "1/4 de Frango de máquina de padaria": "Frango inteiro",
    "Galeto avícola (Franguinho desossado/inteiro)": "Frango inteiro",
    # Pescados
    "Filé desossado de Merluza branca importada": "Merluza (filé)",
    "Costela de Tambaqui": "Tambaqui (peixe)",
    "Peixe Dourada/Tambaqui": "Tambaqui (peixe)",
    "Peixe Pintado limpo (sem couro)": "Pintado (peixe)",
    "Pescado Filhote em cubos": "Pintado (peixe)",
    "Pescado Pintado/Cachara em cubos": "Pintado (peixe)",
    "Costela/Posta de Pacu": "Pacu (peixe)",
    "Pescada branca em tiras": "Pescada (peixe)",
    "Posta de Cavala fresca": "Cavala (peixe)",
    "Tainha peixe do mar em postas firmes": "Tainha (peixe)",
    "Peixe fluvial em pedaços": "Peixe de água doce (posta)",
    "Peixe regional desfiado": "Peixe de água doce (posta)",
    "Pescado Piranha em postas limpas": "Peixe de água doce (posta)",
    "Posta de Peixe (Cavala/Dourado)": "Peixe de mar (posta)",
    "Posta de peixe badejo/namorado/dourado": "Peixe de mar (posta)",
    "Pirarucu seco curado": "Pirarucu seco",
    "Camarão cru limpo": "Camarão fresco",
    "Camarão fresco com casca": "Camarão fresco",
    "Camarão seco regional": "Camarão seco",
    "Camarão seco salgado": "Camarão seco",
    "Carne de siri moída ou desfiada crua": "Carne de siri",
    "Molusco Sururu (sem concha)": "Sururu",
    # Ovos
    "Ovo": "Ovo",
    "Ovo frito simples": "Ovo",
    "Ovo para colar": "Ovo",
    "Ovo para empanar": "Ovo",
    "Ovos": "Ovo",
    "Ovos caipiras fritos": "Ovo",
    "Ovos cozidos": "Ovo",
    "Ovos de granja ligantes": "Ovo",
    "Ovos de granja médios": "Ovo",
    "Ovos estalados": "Ovo",
    "Ovos mexidos ou pochê como topping rápido": "Ovo",
    # Gorduras / óleos
    "Óleo": "Óleo de soja",
    "Óleo de chapa": "Óleo de soja",
    "Óleo de fritura": "Óleo de soja",
    "Óleo de fritura ágil": "Óleo de soja",
    "Óleo de imersão": "Óleo de soja",
    "Óleo de imersão dourada": "Óleo de soja",
    "Óleo de soja": "Óleo de soja",
    "Óleo imersão": "Óleo de soja",
    "Óleo para grelhar": "Óleo de soja",
    "Óleo quente": "Óleo de soja",
    "Azeite ou óleo": "Óleo de soja",
    "Azeite/Óleo": "Óleo de soja",
    "Banha/Óleo": "Banha suína",
    "Azeite": "Azeite de oliva",
    "Azeite comum": "Azeite de oliva",
    "Azeite de oliva": "Azeite de oliva",
    "Azeite doce": "Azeite de oliva",
    "Azeite suave": "Azeite de oliva",
    "Azeite de dendê": "Azeite de dendê",
    "Dendê": "Azeite de dendê",
    "Banha": "Banha suína",
    "Banha colherada": "Banha suína",
    "Banha suína": "Banha suína",
    # Laticínios
    "Manteiga": "Manteiga",
    "Manteiga animal": "Manteiga",
    "Manteiga/Óleo": "Manteiga",
    "Manteiga da terra": "Manteiga de garrafa",
    "Manteiga de garrafa": "Manteiga de garrafa",
    "Manteiga de leite": "Manteiga de garrafa",
    "Creme de leite": "Creme de leite",
    "Creme lácteo denso": "Creme de leite",
    "Leite de coco": "Leite de coco",
    "Leite de coco industrial/fresco": "Leite de coco",
    "Queijo coalho": "Queijo coalho",
    "Queijo minas/coalho": "Queijo coalho",
    "Queijo Mussarela": "Queijo mussarela",
    "Queijo Mussarela em fatia dupla": "Queijo mussarela",
    "Queijo prato ralado": "Queijo prato",
    "Queijo": "Queijo prato",
    "Queijo parmesão": "Queijo parmesão",
    "Queijo ralado polvilhado fresco farto": "Queijo parmesão",
    # Tubérculos / raízes / banana
    "Batata": "Batata inglesa",
    "Batata frita": "Batata inglesa",
    "Batata frita palito": "Batata inglesa",
    "Batata inglesa grande inteira/metades": "Batata inglesa",
    "Batata inglesa lisa frita (palito)": "Batata inglesa",
    "Batata portuguesa (rodelas fritas)": "Batata inglesa",
    "Batata suculenta": "Batata inglesa",
    "Batatas coradas": "Batata inglesa",
    "Batatas rústicas fatiadas grandes com casca (forno)": "Batata inglesa",
    "Fritas ou Purê": "Batata inglesa",
    "Batata palha ensacada": "Batata palha",
    "Batata palha fina": "Batata palha",
    "Batata palha industrial": "Batata palha",
    "Batata palha pronta": "Batata palha",
    "Batata doce rústica": "Batata doce",
    "Macaxeira (mandioca crua)": "Mandioca",
    "Mandioca aipim amarela de panela derretida": "Mandioca",
    "Mandioca branca cozida": "Mandioca",
    "Mandioca cozida": "Mandioca",
    "Mandioca cozida e depois frita": "Mandioca",
    "Mandioca crua em pedaços": "Mandioca",
    "Mandioca roxa ou branca cozida em água": "Mandioca",
    "Banana da terra grelhada": "Banana da terra",
    "Banana frita": "Banana da terra",
    "Banana-da-terra": "Banana da terra",
    # Legumes / verduras / frutas
    "Cenoura": "Cenoura",
    "tiras de cenoura dura": "Cenoura",
    "Tomate": "Tomate",
    "Tomate italiano": "Tomate",
    "Tomate molho": "Tomate",
    "Tomates frescos vermelhos": "Tomate",
    "Salada de Tomate (bruta)": "Tomate",
    "Salada de tomate verde": "Tomate",
    "Salada rápida de tomate": "Tomate",
    "Cebola": "Cebola",
    "Cebola branca abundante": "Cebola",
    "Cebola branca cortada em meias-luas": "Cebola",
    "Cebola chapa": "Cebola",
    "Cebola fatiada": "Cebola",
    "Cebola fatiada em lâminas grossas": "Cebola",
    "Cebola fatiada fina": "Cebola",
    "Cebola picada": "Cebola",
    "Cebola rica": "Cebola",
    "Cebola robusta": "Cebola",
    "Cebolas cortadas em rodelas": "Cebola",
    "Cebola roxa": "Cebola roxa",
    "Pimentão": "Pimentão",
    "Pimentão verde": "Pimentão",
    "Pimentões coloridos": "Pimentão",
    "Couve": "Couve",
    "Couve crua fatiada rapidamente": "Couve",
    "Couve crua/refogada": "Couve",
    "Couve fatiada": "Couve",
    "Couve finamente picada": "Couve",
    "Couve refogada brevemente": "Couve",
    "Couve refogada fina": "Couve",
    "Agrião ou couve": "Couve",
    "Repolho grosso": "Repolho",
    "Salada de Alface": "Alface",
    "Salada de alface lisa": "Alface",
    "Escarola/Chicória": "Escarola/Chicória",
    "Radite (Escarola crua ou levemente murcha)": "Escarola/Chicória",
    "Quiabo limpo sem as pontas": "Quiabo",
    "Palmito": "Palmito",
    "Champignon em conserva fatiado": "Champignon (conserva)",
    "Cogumelos limpos": "Champignon (conserva)",
    "Massa de Milho verde fresco": "Milho verde",
    "Milho": "Milho verde",
    "Fruto Pequi fresco/conserva": "Pequi",
    "Jambu": "Jambu",
    "Jambu pré-branqueado": "Jambu",
    "Folhas de jambu": "Jambu",
    "Folhas de Jambu frescas": "Jambu",
    "Folhas de maniva pré-cozidas": "Maniva (folha de mandioca)",
    "Laranja em rodelas": "Laranja",
    "Limão": "Limão",
    "Limão ou Vinagre branco": "Limão",
    "Limão Tahiti caldoso": "Limão",
    "Castanha/Amendoim": "Amendoim",
    # Temperos / ervas
    "Alho": "Alho",
    "Alho forte": "Alho",
    "Alho laminado (frito crocante)": "Alho",
    "Alho socado": "Alho",
    "Alho triturado": "Alho",
    "Sal": "Sal",
    "Sal marinho": "Sal",
    "Cheiro-verde": "Cheiro-verde",
    "Cebolinha": "Cheiro-verde",
    "Coentro": "Coentro",
    "Pimenta": "Pimenta (fresca)",
    "Pimenta bode": "Pimenta (fresca)",
    "Pimenta de cheiro": "Pimenta (fresca)",
    "Pimenta-de-cheiro": "Pimenta (fresca)",
    "Pimenta doce": "Pimenta (fresca)",
    "Pimenta do reino": "Pimenta do reino",
    "Colorau": "Colorau/Urucum",
    "Urucum": "Colorau/Urucum",
    "Sementes Urucum/Colorau": "Colorau/Urucum",
    "Açafrão": "Açafrão da terra",
    "Açafrão da terra": "Açafrão da terra",
    "Cominho": "Cominho",
    "Louro": "Louro (folha)",
    "Orégano": "Orégano",
    "Hortelã": "Hortelã",
    "Hortelã raminhos": "Hortelã",
    "Manjericão rama": "Manjericão",
    # Condimentos / molhos prontos / extras
    "Vinagre colonial": "Vinagre",
    "Mostarda": "Mostarda",
    "Mostarda semente ou molho": "Mostarda",
    "Ketchup": "Ketchup",
    "Maionese (tempero)": "Maionese",
    "Extrato de tomate no caldo": "Extrato de tomate",
    "Molho de tomate industrial": "Molho de tomate (sachê)",
    "Molho de tomate industrial intenso": "Molho de tomate (sachê)",
    "Molho tomate": "Molho de tomate (sachê)",
    "Molho vermelho por cima": "Molho de tomate (sachê)",
    "Caldo de carne": "Caldo de carne (tablete)",
    "Cachaça": "Cachaça",
    # Líquidos regionais
    "Tucupi": "Tucupi",
    "Açaí de acompanhamento": "Açaí (polpa)",
    "Litro de Açaí puro": "Açaí (polpa)",
    # Preço fixo (não-scrapeável)
    "Sangue avícola misturado em vinagre": "Sangue de aves",
    "Sangue suíno coagulado": "Sangue suíno",
    "Caldo da carne para o pirão": "Água/Subproduto (sem custo)",
}

# ─── Decomposições de COMPOSTOS: nome bruto -> [[base, proporção], ...] ───────
# Proporções somam 1.0 e são ESTIMATIVAS (ver REVISAR).
COMPOSTO = {
    # Angu / polenta (fubá + água; resto é água)
    "Angu de fubá (firme)": [["Fubá de milho", 0.30], ["Água/Subproduto (sem custo)", 0.70]],
    "Angu de milho mole (fubá cru)": [["Fubá de milho", 0.30], ["Água/Subproduto (sem custo)", 0.70]],
    "Polenta em barra (fubá com água/sal/alho)": [["Fubá de milho", 0.40], ["Água/Subproduto (sem custo)", 0.60]],
    "Polenta em blocos frita dourada": [["Fubá de milho", 0.35], ["Óleo de soja", 0.10], ["Água/Subproduto (sem custo)", 0.55]],
    "Polenta frita tiras rústicas": [["Fubá de milho", 0.35], ["Óleo de soja", 0.10], ["Água/Subproduto (sem custo)", 0.55]],
    # Baião
    "Baião (Arroz e feijão misto)": [["Arroz branco", 0.50], ["Feijão de corda", 0.50]],
    # Farofas
    "Farofa": [["Farinha de mandioca", 0.80], ["Óleo de soja", 0.15], ["Cebola", 0.05]],
    "Farofa simples": [["Farinha de mandioca", 0.85], ["Óleo de soja", 0.15]],
    "Farofa amanteigada": [["Farinha de mandioca", 0.80], ["Manteiga", 0.20]],
    "Farofa de manteiga": [["Farinha de mandioca", 0.80], ["Manteiga", 0.20]],
    "Farofa de mandioca tostada": [["Farinha de mandioca", 0.85], ["Manteiga", 0.15]],
    "Farofa fina": [["Farinha de mandioca", 0.85], ["Manteiga", 0.15]],
    "Farofa de dendê": [["Farinha de mandioca", 0.80], ["Azeite de dendê", 0.20]],
    "Farofa de milho em flocos": [["Flocão de milho (cuscuz)", 0.85], ["Manteiga", 0.15]],
    "Farofa de milho ou mandioca": [["Farinha de mandioca", 0.85], ["Manteiga", 0.15]],
    "Farofa rica": [["Farinha de mandioca", 0.70], ["Manteiga", 0.15], ["Ovo", 0.10], ["Cebola", 0.05]],
    "Farofa rica de ovos e cebola": [["Farinha de mandioca", 0.65], ["Ovo", 0.20], ["Cebola", 0.10], ["Manteiga", 0.05]],
    # Feijoadas/tropeiro/tutu
    "Feijão tropeiro leve": [["Feijão carioca", 0.50], ["Farinha de mandioca", 0.25], ["Bacon", 0.10], ["Ovo", 0.10], ["Cebola", 0.05]],
    "Tutu de feijão carioca": [["Feijão carioca", 0.60], ["Farinha de mandioca", 0.30], ["Bacon", 0.10]],
    # Saladas compostas
    "Salada": [["Alface", 0.50], ["Tomate", 0.50]],
    "Salada crua mista": [["Alface", 0.40], ["Tomate", 0.30], ["Cenoura", 0.30]],
    "Salada de alface e cenoura ralada": [["Alface", 0.60], ["Cenoura", 0.40]],
    "Salada de alface e tomate": [["Alface", 0.50], ["Tomate", 0.50]],
    "Salada de rúcula, alface e tomate": [["Rúcula", 0.33], ["Alface", 0.33], ["Tomate", 0.34]],
    "Salada mista": [["Alface", 0.40], ["Tomate", 0.30], ["Cenoura", 0.30]],
    "Salada mista colorida crua": [["Alface", 0.40], ["Tomate", 0.30], ["Cenoura", 0.30]],
    "Salada mista tropical": [["Alface", 0.40], ["Tomate", 0.30], ["Cenoura", 0.30]],
    "Salada mista verde folhosa": [["Alface", 0.50], ["Rúcula", 0.50]],
    "Salada verde": [["Alface", 0.50], ["Rúcula", 0.50]],
    "Salada repolho agridoce e cítrico (chucrute adapt.)": [["Repolho", 0.85], ["Cenoura", 0.10], ["Limão", 0.05]],
    "Salada de maionese de batata cremosa": [["Batata inglesa", 0.70], ["Maionese", 0.20], ["Cenoura", 0.10]],
    "Salada densa de maionese batata com cheiro verde": [["Batata inglesa", 0.65], ["Maionese", 0.20], ["Cenoura", 0.10], ["Cheiro-verde", 0.05]],
    "Maionese de batata (tubérculos grossos)": [["Batata inglesa", 0.70], ["Maionese", 0.20], ["Cenoura", 0.10]],
    # Vinagrete
    "Vinagrete": [["Tomate", 0.40], ["Cebola", 0.30], ["Pimentão", 0.10], ["Vinagre", 0.10], ["Óleo de soja", 0.05], ["Cheiro-verde", 0.05]],
    "Vinagrete em ácido acético": [["Tomate", 0.40], ["Cebola", 0.30], ["Pimentão", 0.10], ["Vinagre", 0.10], ["Óleo de soja", 0.05], ["Cheiro-verde", 0.05]],
    # Molhos rústicos (tomate + refogado)
    "Molho de tomate farto": [["Tomate", 0.70], ["Cebola", 0.15], ["Alho", 0.05], ["Óleo de soja", 0.10]],
    "Molho de tomate rústico encorpado": [["Tomate", 0.70], ["Cebola", 0.15], ["Alho", 0.05], ["Óleo de soja", 0.10]],
    # Purês
    "Purê de batata": [["Batata inglesa", 0.80], ["Manteiga", 0.10], ["Leite", 0.10]],
    "Purê de batata inglesa sedoso macio amarelado": [["Batata inglesa", 0.80], ["Manteiga", 0.10], ["Leite", 0.10]],
    "Purê de batata ou farofa simples": [["Batata inglesa", 0.80], ["Manteiga", 0.10], ["Leite", 0.10]],
    "Purê de Macaxeira (Mandioca)": [["Mandioca", 0.80], ["Manteiga", 0.10], ["Leite", 0.10]],
    "Purê de abóbora cabotiá": [["Abóbora", 0.85], ["Manteiga", 0.10], ["Leite", 0.05]],
    # Pirão (farinha + caldo subproduto)
    "Pirão": [["Farinha de mandioca", 0.40], ["Água/Subproduto (sem custo)", 0.60]],
    "Pirão capixaba grosso": [["Farinha de mandioca", 0.40], ["Água/Subproduto (sem custo)", 0.60]],
    "Pirão de farinha": [["Farinha de mandioca", 0.40], ["Água/Subproduto (sem custo)", 0.60]],
    "Pirão de peixe (extrato de cabeças espesso)": [["Farinha de mandioca", 0.40], ["Água/Subproduto (sem custo)", 0.60]],
    # Massas
    "Massa (Trigo, leite, ovo)": [["Farinha de trigo", 0.70], ["Ovo", 0.20], ["Leite", 0.10]],
    "Massa crua de Nhoque (trigo/batata amido puro)": [["Batata inglesa", 0.60], ["Farinha de trigo", 0.40]],
    "Massa podre de empada (banha/trigo)": [["Farinha de trigo", 0.70], ["Banha suína", 0.30]],
    "Massa rústica (arroz, queijo, ovo, leite)": [["Arroz branco", 0.50], ["Queijo coalho", 0.20], ["Ovo", 0.20], ["Leite", 0.10]],
    # Recheios
    "Recheio de Carne moída refogada seca": [["Carne moída bovina", 0.80], ["Cebola", 0.10], ["Tomate", 0.10]],
    "Recheio de frango, guariroba, ovos": [["Peito de frango", 0.60], ["Guariroba", 0.25], ["Ovo", 0.15]],
    # Caruru / Vatapá (baianos)
    "Caruru (guarnições)": [["Quiabo", 0.60], ["Camarão seco", 0.15], ["Azeite de dendê", 0.10], ["Cebola", 0.10], ["Amendoim", 0.05]],
    "Vatapá": [["Pão francês", 0.30], ["Leite de coco", 0.25], ["Camarão seco", 0.15], ["Azeite de dendê", 0.10], ["Amendoim", 0.10], ["Cebola", 0.10]],
    # Caldo de tucupi
    "Caldo de Tucupi temperado": [["Tucupi", 0.90], ["Cebola", 0.05], ["Alho", 0.05]],
    # Outros multi-item
    "Base láctea (creme de leite), Ketchup": [["Creme de leite", 0.60], ["Ketchup", 0.40]],
    "Creme de leite, Ketchup e Mostarda": [["Creme de leite", 0.50], ["Ketchup", 0.30], ["Mostarda", 0.20]],
    "Carnes salgadas, linguiça defumada": [["Carne seca/Charque", 0.50], ["Linguiça defumada", 0.50]],
    "Batata e Cenoura": [["Batata inglesa", 0.50], ["Cenoura", 0.50]],
    "Radite (chicória) com cubos de bacon dourados": [["Escarola/Chicória", 0.85], ["Bacon", 0.15]],
}

# ─── Pontos de baixa confiança para revisão ──────────────────────────────────
# nome bruto -> motivo
REVISAR = {
    "Arroz Arbório ou branco especial longo": "Arbório (risoto) ou branco? assumi arroz branco.",
    "Azeite ou óleo": "Ambíguo azeite/óleo; assumi óleo de soja (mais barato).",
    "Azeite/Óleo": "Ambíguo azeite/óleo; assumi óleo de soja.",
    "Banha/Óleo": "Ambíguo banha/óleo; assumi banha suína.",
    "Manteiga/Óleo": "Ambíguo manteiga/óleo; assumi manteiga.",
    "Azeite": "Tratado como azeite de oliva (padrão BR); verificar se era óleo comum em contexto N/NE.",
    "Manteiga de leite": "Manteiga de leite nordestina ≈ manteiga de garrafa; confirmar.",
    "Banana frita": "Assumi banana da terra; pode ser banana nanica.",
    "Feijão manteiguinha (Santarém)": "Variedade amazônica específica; agrupei em feijão de corda.",
    "Feijão verde fresco": "Feijão verde = corda fresco; confirmar.",
    "Feijão verde manteiguinha": "Variedade específica; agrupei em feijão de corda.",
    "Feijão marrom ou negro": "Ambíguo marrom/negro; assumi feijão preto.",
    "Carne bovina cortada (iscas)": "Corte não especificado; assumi coxão mole.",
    "Bife bovino selado rapidamente (ponto macio)": "Corte não especificado; assumi coxão mole.",
    "Carne bovina (Contrafilé/Alcatra)": "Dois cortes; assumi alcatra.",
    "Carne em tiras (Alcatra/Mignon/Patinho)": "Três cortes; assumi alcatra.",
    "Carne picada (Coxão duro/Patinho)": "Dois cortes; assumi patinho.",
    "Costela/Alcatra/Vazio assados brasa (1 hora)": "Churrasco misto; assumi costela bovina como representante.",
    "Matambre bovino aberto": "Corte regional (matambre/fraldinha); manter base própria?",
    "Lombo/Pernil suíno em iscas": "Lombo ou pernil; assumi pernil.",
    "Linguiça toscana/calabresa de porco": "Toscana ou calabresa; assumi toscana.",
    "Salsichão campeiro (linguiça grossa de churrasco)": "Agrupado em linguiça toscana; confirmar.",
    "Miúdos de porco/Carne seca": "Dois itens; assumi miúdos suínos.",
    "Queijo": "Tipo não especificado; assumi queijo prato.",
    "Queijo minas/coalho": "Minas ou coalho; assumi coalho.",
    "Queijo ralado polvilhado fresco farto": "Ralado geralmente parmesão; confirmar.",
    "Tomate molho": "Tomate para molho (in natura); confirmar se não é molho pronto.",
    "Molho tomate": "Assumi molho pronto (sachê); pode ser molho rústico.",
    "Molho vermelho por cima": "Assumi molho pronto (sachê); confirmar.",
    "Pimenta": "Tipo não especificado; assumi pimenta fresca (pode ser pimenta do reino).",
    "Castanha/Amendoim": "Castanha (caju/pará) ou amendoim; assumi amendoim.",
    "Caldo de carne": "Pode ser tablete industrial OU caldo natural (subproduto); assumi tablete.",
    "Cogumelos limpos": "Assumi champignon em conserva; pode ser fresco (paris/shiitake).",
    "Peixe Dourada/Tambaqui": "Dois peixes; assumi tambaqui.",
    "Posta de Peixe (Cavala/Dourado)": "Genérico de mar; base 'peixe de mar (posta)'.",
    "Posta de peixe badejo/namorado/dourado": "Genérico de mar; base 'peixe de mar (posta)'.",
    "Peixe regional desfiado": "Espécie não especificada; base genérica água doce.",
    "Pescado Filhote em cubos": "Filhote = pintado jovem; agrupei em pintado.",
    "Pescado Piranha em postas limpas": "Piranha; base genérica água doce.",
    "Pão de alho bisnaga cremosa (forno)": "Tratado como produto pronto de varejo (bisnaga).",
    "Torresmo": "Tratado como produto pronto; pode ser feito de panceta.",
    "Farinha de Uarini": "Farinha amazônica premium; agrupada em farinha de mandioca.",
    "Farinha d'água / Tapioca": "Farinha d'água ou tapioca; assumi farinha de mandioca.",
    "Milho": "Milho verde ou de pipoca/seco? assumi milho verde.",
    "Agrião ou couve": "Agrião ou couve; assumi couve.",
    "Fritas ou Purê": "Batata frita ou purê; assumi batata inglesa (base comum).",
    "Pão dormido ou farinha de trigo": "Pão ou farinha; assumi pão francês.",
    "Limão ou Vinagre branco": "Limão ou vinagre; assumi limão.",
    # Decomposições (todas as proporções são estimativas)
    "Angu de fubá (firme)": "Proporção fubá/água estimada.",
    "Angu de milho mole (fubá cru)": "Proporção fubá/água estimada.",
    "Polenta em barra (fubá com água/sal/alho)": "Proporção fubá/água estimada.",
    "Polenta em blocos frita dourada": "Proporção estimada (fubá/óleo/água).",
    "Polenta frita tiras rústicas": "Proporção estimada (fubá/óleo/água).",
    "Baião (Arroz e feijão misto)": "Proporção arroz/feijão estimada 50/50.",
    "Farofa": "Composição/proporção estimada.",
    "Farofa simples": "Composição/proporção estimada.",
    "Farofa amanteigada": "Composição/proporção estimada.",
    "Farofa de manteiga": "Composição/proporção estimada.",
    "Farofa de mandioca tostada": "Composição/proporção estimada.",
    "Farofa fina": "Composição/proporção estimada.",
    "Farofa de dendê": "Composição/proporção estimada.",
    "Farofa de milho em flocos": "Composição/proporção estimada.",
    "Farofa de milho ou mandioca": "Mandioca ou milho; assumi mandioca; proporção estimada.",
    "Farofa rica": "Composição/proporção estimada.",
    "Farofa rica de ovos e cebola": "Composição/proporção estimada.",
    "Feijão tropeiro leve": "Composição/proporção estimada.",
    "Tutu de feijão carioca": "Composição/proporção estimada.",
    "Salada": "Composição genérica estimada (alface/tomate).",
    "Salada crua mista": "Composição estimada.",
    "Salada de alface e cenoura ralada": "Proporção estimada.",
    "Salada de alface e tomate": "Proporção estimada.",
    "Salada de rúcula, alface e tomate": "Proporção estimada.",
    "Salada mista": "Composição estimada.",
    "Salada mista colorida crua": "Composição estimada.",
    "Salada mista tropical": "Composição estimada (pode levar frutas).",
    "Salada mista verde folhosa": "Composição estimada.",
    "Salada verde": "Composição estimada.",
    "Salada repolho agridoce e cítrico (chucrute adapt.)": "Composição estimada.",
    "Salada de maionese de batata cremosa": "Composição/proporção estimada.",
    "Salada densa de maionese batata com cheiro verde": "Composição/proporção estimada.",
    "Maionese de batata (tubérculos grossos)": "Composição/proporção estimada.",
    "Vinagrete": "Composição/proporção estimada.",
    "Vinagrete em ácido acético": "Composição/proporção estimada.",
    "Molho de tomate farto": "Molho rústico; composição estimada.",
    "Molho de tomate rústico encorpado": "Molho rústico; composição estimada.",
    "Purê de batata": "Composição/proporção estimada.",
    "Purê de batata inglesa sedoso macio amarelado": "Composição/proporção estimada.",
    "Purê de batata ou farofa simples": "Purê ou farofa; assumi purê; proporção estimada.",
    "Purê de Macaxeira (Mandioca)": "Composição/proporção estimada.",
    "Purê de abóbora cabotiá": "Composição/proporção estimada.",
    "Pirão": "Caldo tratado como subproduto sem custo; proporção estimada.",
    "Pirão capixaba grosso": "Caldo subproduto; proporção estimada.",
    "Pirão de farinha": "Caldo subproduto; proporção estimada.",
    "Pirão de peixe (extrato de cabeças espesso)": "Caldo de peixe subproduto; proporção estimada.",
    "Massa (Trigo, leite, ovo)": "Composição/proporção estimada.",
    "Massa crua de Nhoque (trigo/batata amido puro)": "Composição/proporção estimada.",
    "Massa podre de empada (banha/trigo)": "Composição/proporção estimada.",
    "Massa rústica (arroz, queijo, ovo, leite)": "Composição/proporção estimada.",
    "Recheio de Carne moída refogada seca": "Composição/proporção estimada.",
    "Recheio de frango, guariroba, ovos": "Composição/proporção estimada (guariroba = palmito amargo).",
    "Caruru (guarnições)": "Composição/proporção estimada.",
    "Vatapá": "Receita complexa; composição/proporção estimada.",
    "Caldo de Tucupi temperado": "Proporção estimada.",
    "Base láctea (creme de leite), Ketchup": "Proporção estimada.",
    "Creme de leite, Ketchup e Mostarda": "Proporção estimada.",
    "Carnes salgadas, linguiça defumada": "Dois itens; proporção estimada.",
    "Batata e Cenoura": "Proporção estimada 50/50.",
    "Radite (chicória) com cubos de bacon dourados": "Proporção estimada.",
    # Sem cotação
    "Sangue avícola misturado em vinagre": "Sem cotação de varejo (cabidela); preço fixo de R$0,50.",
    "Sangue suíno coagulado": "Sem cotação de varejo (sarapatel); preço fixo de R$0,50.",
    "Caldo da carne para o pirão": "Subproduto da carne; sem custo próprio.",
}

# ─── Camada de CONSOLIDAÇÃO (síntese para caber no orçamento de API) ──────────
# Aplicada POR CIMA do mapa detalhado: base_original -> base_consolidada.
# Reduz o nº de termos de busca distintos. Regras definidas pelo responsável
# (9 regras explícitas) + fusões seguras de variantes equivalentes.
# Bases não citadas aqui permanecem como estão.
CONSOLIDA = {
    # EXPLOSÃO de 12/07/2026 (decisão do responsável, com folga de API):
    # as fusões de cortes bovinos, carne seca/sol, linguiças, lombo/pernil,
    # bacon/panceta, queijos, fubá/flocão, molho/extrato, folhas e pimentas
    # foram DESFEITAS — cada base volta a ter cotação própria. Ficaram apenas
    # as fusões de peixes (2ª rodada), coxão duro, fradinho, cebola e manteiga.
    #
    # — Coxão duro segue em Alcatra (genérico). Mignon, contrafilé, coxão mole,
    #   patinho e carne moída foram DES-consolidados (cotação própria, nome fiel).
    "Coxão duro bovino":   "Alcatra bovina",
    # — Peixe genérico de mar → Pescada (cavala/tainha des-consolidados).
    #   RODADA 2 (decisões do responsável em 12/07/2026, implementar após
    #   validar a 1ª explosão na coleta de segunda):
    #     · "Posta de Peixe (Cavala/Dourado)" (Moqueca NE)      → Cavala (base já existe)
    #     · "Posta de peixe (Pescada/Tucunaré)" (Caldeirada N)  → Tucunaré (termo novo)
    #     · "Posta badejo/namorado/dourado" (Moqueca Capixaba)  → Badejo/Namorado (termo novo)
    #     · "Pescada branca em tiras"                           → fica em Pescada
    "Peixe de mar (posta)":    "Pescada (peixe)",
    # — Peixe genérico de rio → Pintado (tambaqui/pacu des-consolidados).
    #   RODADA 2:
    #     · "Pescado Filhote em cubos" (Guisado N) → Filhote/Piraíba (termo novo,
    #       busca "filé de piraíba filhote", nao: piramutaba/pirara/tilápia;
    #       certamente coberto por preço manual — sem oferta online)
    #     · "Pescado Piranha em postas" (Caldo CO) → Piranha (preço manual)
    #     · "Peixe fluvial (Lambari/Traíra)"       → Lambari/Traíra (termo novo)
    #     · "Peixe regional desfiado" (Mujica N) e Pintado/Cachara → ficam em Pintado
    "Peixe de água doce (posta)":"Pintado (peixe)",
    # — Regra: feijão fradinho = feijão de corda
    "Feijão fradinho":     "Feijão de corda",
    # — Regra: cebola única (roxa e branca)
    "Cebola roxa":         "Cebola",
    # — Manteiga de garrafa segue em Manteiga
    "Manteiga de garrafa": "Manteiga",
}

# Categorias de bases novas (para a aba Ingredientes Canônicos)
BASE.update({
    "Feijão branco":               "Leguminosa",   # criado p/ Dobradinha à Paulista (12/07/2026)
})

# ─── Receitas extras (pratos que não estão na planilha original) ─────────────
# Linhas em nível de base canônica FINAL: (região, prato, base, PB g, PC g).
# Dobradinha à Paulista PF: planilha do sócio de 12/07/2026 (entra no lugar do
# Estrogonofe de Carne Bovina, que fica inativo). O composto cebola/alho/
# cheiro-verde/sal (30g→24g) foi decomposto nas proporções usuais de refogado.
RECEITAS_EXTRA = [
    ("Sudeste", "11. Dobradinha à Paulista PF", "Bucho/Dobradinha bovina", 150.0, 90.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Feijão branco",            50.0, 130.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Linguiça calabresa",       40.0, 35.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Arroz branco",             60.0, 150.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Extrato de tomate",        20.0, 20.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Óleo de soja",             15.0, 15.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Limão",                    30.0, None),  # limpeza, descartado
    ("Sudeste", "11. Dobradinha à Paulista PF", "Cebola",                   15.0, 12.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Alho",                      5.0, 4.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Cheiro-verde",              5.0, 4.0),
    ("Sudeste", "11. Dobradinha à Paulista PF", "Sal",                       5.0, 4.0),
]

# Pratos mantidos no banco mas FORA de tabelas, gráficos e índice (pratos.ativo=false)
PRATOS_INATIVOS = {
    ("Sudeste", "11. Estrogonofe de Carne Bovina"),   # substituído pela Dobradinha (12/07/2026)
}


def consolidar(base):
    """Aplica a camada de consolidação a um nome-base."""
    return CONSOLIDA.get(base, base)


# ─── Correção de nomes de prato inconsistentes na planilha original ──────────
# A 1ª linha do prato 4 do Norte veio como "...(Adaptado para PF)" e as demais
# como "4. Tacacá Reforçado", partindo o prato em dois. Unifica.
PRATO_ALIAS = {
    "4. Tacacá Reforçado (Adaptado para PF)": "4. Tacacá Reforçado",
    # grafia errada na planilha original — o correto é Mujica (12/07/2026)
    "20. Majica de Peixe": "20. Mujica de Peixe",
}

